# This is a basic workflow to help you get started with Actions
name: Example workflow

# Controls when the workflow will run
on:
  push:

jobs:
  hello:
    runs-on: macos-latest
    steps:
      - run: echo "Hello, World"
      - run: |
          echo look ma
          echo "I'm a two-liner!"

  drive-test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd example-py-unittest
          python -m unittest discover
